### ISSUE TITLE
Environment variables missing in exercise 3

### ISSUE THREAD

**Issue by toddwhitehead** [Microsoft/MCW-IoT-for-business#14]
Excercise 3 describes changing the value for the project environment settings for both the simulation agent and storage adapter projects but the environment variable arent present and need to be created.

https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#exercise-3-create-bus-and-traffic-light-simulated-devices-and-add-alerts-and-filters

**Comment by eiriniasteri** [comment]
Has this issue been resolved or are you planning to resolve it soon?

Thanks!

**Comment by mrfalafel** [comment]
It has been resolved and the PR is awaiting approval
Thanks
