### ISSUE TITLE
Missing files from the project for devicemodels

### ISSUE THREAD

**Issue by mrfalafel** [Microsoft/MCW-IoT-for-business#4]
The device model files required for the project are not checked in.
![missing files_iotforbusiness](https://user-images.githubusercontent.com/1494257/44357016-fe0e8880-a47e-11e8-80fb-91eb8e9dd258.png)

**Comment by mrfalafel** [comment]
Corrected in august fix

**Comment by ravitola** [comment]
I am trying to add my own device and have created the JSON files in the Services\data\devicemodels  and in the JS scripts in the scripts folder. 

However, when I follow the steps and Debug the SimulationAgent the custom devices aren't found.  

It looks like as part of the build process, the device models are copied to \Lab-files\azure-iot-pcs-remote-monitoring-dotnet\device-simulation\SimulationAgent\bin\Debug\netcoreapp2.0\data\devicemodels

Is there a step I am missing to add my files the build recipe ?
