### ISSUE TITLE
I don't see any IOTLab folder into lab VM. 

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-IoT-for-business#8]
I don't see any IOTLab folder into lab VM. Can you suggest from wher I can download the lab files. 
You removed the URL to download the lab files from Before hands on lab guide.

**Comment by DawnmarieDesJardins** [comment]
Adding Lino - Please review & respond.
Thanks!

**Comment by mrfalafel** [comment]
All the code is checked in under Hand-on-lab/Lab-files, which was decided to be moved there instead of including a zip file.

**Comment by akn9050** [comment]
That is fine, but it should be undated in lab guide where user can find the lab files and how users can copy in there lab VM using git clone. Also screenshot and content is not matching in exercise 1 and task 1 of HOL step-by-step - IoT for business.md.
To run the PCS commands user need to change the directory to  the directory where PCS is installed.
As per lab guide I was running the PCS command here "C:\IoTLab \azure-iot-pcs-remote-monitoring-dotnet\cli". But it is showing pcs is not recognized as any cmdlet.

Then I searched for directory where pcs is installed and switched to that directory then I am able to run pcs command in that directory.

**Comment by akn9050** [comment]
Not Able to login with PCS login

![snag_deeb3ed](https://user-images.githubusercontent.com/27498287/47289015-652ef180-d616-11e8-8cf7-db41f08d9329.png)

**Comment by joelhulen** [comment]
I have this updated in the new version of the docs which will be committed for review today.

Thanks for the heads-up.

**Comment by akn9050** [comment]
Okay, Please let me know once it is done.

**Comment by joelhulen** [comment]
This and other changes can be found in the october-2018-testfix branch.
