### ISSUE TITLE
Not able to login with PCS Login

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-IoT-for-business#9]
Hi 

I am not able to login with PCS login. 
C:\Users\demouser\AppData\Roaming\npm>pcs login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BNH8DJU5A to authenticate.
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.mkdir (fs.js:719:14)
    at ms_rest_azure_1.interactiveLoginWithAuthResponse.then (C:\IoTLab\azure-iot-pcs-remote-monitoring-dotnet\cli\publish\index.js:229:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

![snag_df0ab29](https://user-images.githubusercontent.com/27498287/47289074-b0e19b00-d616-11e8-99d0-77f7ed6fe13f.png)

**Comment by akn9050** [comment]
https://github.com/Azure/pcs-cli/commit/eb8381ea33b305670054c7f15ba1c93b1baa24ee

Please see this you need to modify index.js file in lab files.

**Comment by akn9050** [comment]
You have to make change in index.js file 
Please see https://github.com/Azure/pcs-cli/commit/eb8381ea33b305670054c7f15ba1c93b1baa24ee

**Comment by joelhulen** [comment]
This change will be included in the new version of the docs, which will be committed for review today.

Thank you.

**Comment by akn9050** [comment]
Please let me know if there is any update.

**Comment by joelhulen** [comment]
This was resolved with the latest updates to the october-2018-testfix branch. The changes will be merged in after review.
